### ISSUE TITLE
append a route to new-cluster-cidr in old container

### ISSUE THREAD

**Issue by fzu-huang** [openshift/sdn#170]
I use openshift-sdn with a small cluster-network in my cluster for a long time, now i find that this cluster-network has beed used up 
 when i want to add more nodes into my cluster. 

i change args or update `clusternetworks` ,anyway ,now i add a new cidr `10.132.0.0/14` in my cluster-network: `default`  

```
# kubectl  get clusternetwork -oyaml 
apiVersion: v1
items:
- apiVersion: network.openshift.io/v1
  clusterNetworks:
  - CIDR: 10.178.40.0/21
    hostSubnetLength: 10
  - CIDR: 10.132.0.0/14
    hostSubnetLength: 8
  hostsubnetlength: 10
  kind: ClusterNetwork
  metadata:
    creationTimestamp: 2020-07-09T03:04:22Z
    generation: 1
    name: default
    namespace: ""
    resourceVersion: "36528919"
    selfLink: /apis/network.openshift.io/v1/clusternetworks/default
    uid: e3b4a921-c190-11ea-b605-fa163e6fe7d6
  network: 10.178.40.0/21
  pluginName: redhat/openshift-ovs-multitenant
  serviceNetwork: 10.178.32.0/21
  vxlanPort: 4789
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

but as this [doc](https://docs.openshift.com/container-platform/3.6/install_config/configuring_sdn.html#configuring-the-pod-network-on-masters) said ,   node must be delete and re-creating ,  I have some pod running on these node that can not be shutdown.

Then I found  this pr : https://github.com/openshift/sdn/commit/38780ce90cf25bdabe23c90f1fdda53796b706fd   . As I know ,I can restart  sdn-agent-pod on node  to re-build routes/iptables/openflows for new cidr in clusternetwork,  it will not cause my pod-container re-create (it will call `reattach` method)

But in this way, all existing pods' containers cann't connect to new cidr, because of lack of route to new cidr. Why don't agent inject a route to new cidr  into old container  when it do `reattach container ` ?

**Comment by danwinship** [comment]
> Why don't agent inject a route to new cidr into old container when it do `reattach container ` ?

Because we don't support changing the cluster network without restarting, so therefore there is no need to modify the pod routes because they can't have changed unless you did something unsupported. You're basically just asking "why doesn't the code implement the feature that it doesn't implement".

At this point new development is going into ovn-kubernetes and we are not adding new features to openshift-sdn.

/close
