### ISSUE TITLE
when kube-proxy is disabled, sdn should not startMetricsServer 

### ISSUE THREAD

**Issue by fzu-huang** [openshift/sdn#231]
I have deploy openshift-sdn successfully and  update it by edit configmap `sdn-config`:

```
mode: "disabled"
```

after that I deploy a kube-proxy ,and RE-DEPLOY  sdn again, this time, sdn pod stuck in phase: RunContainerError. logs:

```
W1210 10:17:38.676349   44123 proxy.go:63] Built-in kube-proxy is disabled
E1210 10:17:38.678956   44123 proxy.go:254] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
I1210 10:17:38.701436   44123 multitenant.go:158] SyncVNIDRules: 0 unused VNIDs
E1210 10:17:43.679198   44123 proxy.go:254] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
E1210 10:17:48.681093   44123 proxy.go:254] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use

```

I tried update  sdn‘s configmap to erase kube-proxy-metric-addr:

```
metricsBindAddress: ""
```

but seem uneless. 

I check the code and found that :

```
func (sdn *OpenShiftSDN) runProxy(waitChan chan<- bool) {
	if string(sdn.ProxyConfig.Mode) == "disabled" {
		klog.Warningf("Built-in kube-proxy is disabled")
		sdn.startMetricsServer()
		close(waitChan)
		return
	}
...
func (sdn *OpenShiftSDN) startMetricsServer() {
	if sdn.ProxyConfig.MetricsBindAddress == "" {
		return
	}
```

I think maybe we should cancel  call `sdn.startMetricsServer()` if sdn.ProxyConfig.Mode is "disabled"

**Comment by fzu-huang** [comment]
@danwinship CC,please.  If it really need an optimaze , I'm glad to open a pullrequest to resolve it

**Comment by danwinship** [comment]
Running openshift-sdn with kube-proxy disabled is not supported. The mode only exists for our own internal testing purposes. Where did you even learn about this config option?
/close
